services:
  jupyter: 
    image: assg1-p5
    env_file:
    - .env
    volumes:
      - ./:/problem5
    ports:
      - 8888:8888
    networks:
        - dbnetwork

  postgres:
    image: postgres:latest
    env_file:
    - .env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
        - dbnetwork

volumes:
    postgresdata:

networks:
    dbnetwork: